### ISSUE TITLE
Kernel Panic OS X

### ISSUE THREAD

**Issue by dannyvassallo** [lord/middleman-php#12] opened 2015-03-17 21:40 UTC
It's probably just my app and the way I'm using this gem, but I get kernel panics every once in a while using this. I had live-reload on and I figured that was the issue, but since disabling it I still get a panic once in a little while.

With that being said -- I love this gem.

**Comment by lord** [comment] 2015-03-18 04:55
Glad you like it! Sorry you're having issues. It doesn't really sound like the kind of problem I'd be able to solve. You're sure the problem is `middleman-php`, and not some PHP or Ruby thing? The code in this project is pretty mundane.

I'm going to close this because it doesn't seem too definite right now, but if you have more information, or if anybody else is also having this problem, I'd love to hear it!

**Closed by lord** 2015-03-18 04:55 UTC
